---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  labels:
    name: ping-service
    app: demo-ping-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
  selector:
    name: ping-app-pod
    app: demo-ping-app
